my:
 name: qilin
 age: 18
 number:  ${random.int}
 uuid : ${random.uuid}
 max: ${random.int(10)}
 value: ${random.value}
 greeting: hi,i'm  ${my.name}

spring:
  profiles:
    active: dev
  redis:
    host: 127.0.0.1
    port: 6379


